### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by takeda** [benkehoe/aws-error-utils#4]
This looks nice, but it would really help to have type annotation.

Would it be possible to add that?

**Comment by benkehoe** [comment]
Can you elaborate on what it would "really help" with? Given that it's currently using `namedtuple` and `*args, **kwargs`, it would potentially require a major version bump to add meaningful type annotations. Understanding what obstacle the lack of type annotations is putting up would help me.

**Comment by takeda** [comment]
So I guess I've been spoiled, but if you use IDE that understand type annotations like PyCharm you get additional benefits such as:

- autocomplete
- highlighting errors (it catches many errors where wrong type is used, it's especially good and alerting that value could be None)
- refactoring (moving function around, changing signatures or function names) just works

Boto3 is missing types as well, but someone made a stub for them, so if you use PyCharm and also install boto3-stubs package (for example `poetry add boto3-stubs[ec2]`) you will get all these benefits.

Additional benefit is that if the entire code is typed one can use mypyc (looks like Cython also might be adding support for them) to compile it to improve performance

**Comment by benkehoe** [comment]
This is released in [v2.4](https://github.com/benkehoe/aws-error-utils/blob/master/CHANGELOG.md#v24)
