### ISSUE TITLE
Raising client exceptions for tests

### ISSUE THREAD

**Issue by w0rmr1d3r** [benkehoe/aws-error-utils#5]
Hi @benkehoe !

Thank you for such an amazing repo!

I have a question, have you tried or do you have an example with a test where you raise a client exception and verify that is being handled correctly?

I wanted to write some unit tests for that but can't find a way with `aws-error-utils`.

Thank you!

**Comment by benkehoe** [comment]
Are you looking for a way to manufacture `botocore.exceptions.ClientError` to raise in your test? For example, if I added something like this:
```python
def make_client_error(code, message, operation_name, http_status_code=None, response=None):
    if response is None:
        response = {}
    else:
        response = response.copy()
    response["Error"] = {
        "Code": code,
        "Message": message
    }
    if http_status_code:
        if "ResponseMetadata" not in response:
            response["ResponseMetadata"] = {}
        else:
            response["ResponseMetadata"] = response["ResponseMetadata"].copy()
    return ClientError(response, operation_name)
```
and then in a test you could do something like
```python
try:
    raise make_client_error("NoSuchBucket", "Bucket does not exist", "GetObject", 404)
except errors.NoSuchBucket:
    pass
except Exception:
    assert False, "Did not catch ClientError"
```
is this what you're looking for?

**Comment by w0rmr1d3r** [comment]
Yes! Thank you @benkehoe !

Could we add that function `make_client_error` as part of this repo?

Thank you again!

**Comment by benkehoe** [comment]
Just pushed this as [v1.3](https://github.com/benkehoe/aws-error-utils/blob/master/CHANGELOG.md#v13).
